name: First Workflow

on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      message:
        description: Greet message
        type: text
        default: World

jobs:
  HelloJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - run: echo Hello ${{ github.event.inputs.message }}
      name: Greeting Command
    - name: Check Event
      run: echo ${{ github['event_name'] }} 
    - run: cat todolist.txt
